KPMG/KPMG/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace KPMG.Models
{
    public class Department
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public IEnumerable<Employee> Employees { get; set; }
    }
}

KPMG/KPMG/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using KPMG.Enums;
using System.ComponentModel.DataAnnotations;

namespace KPMG.Models
{
    public class Employee
    {
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required, DataType(DataType.Date), Display(Name = "Hire date"), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime HireDate { get; set; }
        [Required]
        public Department Department { get; set; }
        [Required]
        public Grade Grade { get; set; }
        [Display(Name = "Performance Manager")]
        public Employee PerformanceManager { get; set; }

        [Display(Name = "Full Name")]
        public string Fullname => LastName + " " + FirstName;
    }
}

KPMG/KPMG/Controllers/EmployeesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using KPMG.DAL;
using KPMG.Models;

namespace KPMG.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly Filters _filters = new Filters();
        private readonly ControlsHelpers _controlHelper = new ControlsHelpers();

        // GET: Employees
        public ActionResult Index()
        {
            var employees = _filters.GetAllEmployees();

            ViewBag.departmentsList = _controlHelper.GetDepartmentsList();
            ViewBag.gradesList = _controlHelper.GetGradesList();
            ViewBag.perfManList = _controlHelper.GetPerformanceManagerList();

            return View(employees.ToList());
        }

        [HttpPost]
        public ActionResult FilterResults(string filterId, string value)
        {
            List<Employee> employeesList;
            switch (filterId)
            {
                case "hireDateFilter":
                    employeesList = _filters.HireDateFilter(value).ToList();
                    break;
                case "departmentsList":
                    employeesList = _filters.DepartmentFilter(value).ToList();
                    break;
                case "gradesList":
                    employeesList = _filters.GradeFilter(value).ToList();
                    break;
                case "perfManList":
                    employeesList = _filters.ManagerFilter(value).ToList();
                    break;
                default:
                    employeesList = _filters.NameFilter(value).ToList();
                    break;
            }
            return PartialView("Filter", employeesList);
        }

        [HttpPost]
        public JsonResult Autocompleter()
        {
            var suggestions = _controlHelper.GetSuggestions();
            return Json(suggestions);
        }
    }
}

KPMG/KPMG/Controllers/HomeController.cs
using System.Web.Mvc;

namespace KPMG.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult About()
        {
            ViewBag.Message = "Application description";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Developer information";

            return View();
        }
    }
}

KPMG/KPMG/Views/Employees/Index.cshtml
@model IEnumerable<KPMG.Models.Employee>

@{
    ViewBag.Title = "KPMG Employees";
}

<h2>Employees</h2>

<button id="filterButton" type="button" class="btn btn-default" onclick="showFilters()">Show filters</button>
<section id="filters" style="display: none">
    <article class="col-sm-4">
        <label>Search name: </label>
        <input type="text" id="nameFilter" class="form-control"/>
        <label>Hired after: </label>
        <input type="date" id="hireDateFilter" class="form-control"/>
    </article>
    <article class="col-sm-4">
        <label>Department: </label>
        @Html.DropDownList("departmentsList", new SelectList(ViewBag.departmentsList.Items), "Any", new {@class = "form-control"})
        <label>Grade: </label>
        @Html.DropDownList("gradesList", new SelectList(ViewBag.gradesList.Items), "Any", new {@class = "form-control"})
    </article>
    <article class="col-sm-4">
        <label>Performance Manager: </label>
        @Html.DropDownList("perfManList", new SelectList(ViewBag.perfManList.Items), "Any", new {@class = "form-control"})
    </article>   
</section>
<p>
    <div id="contentSection">
        @Html.Partial("Filter");
    </div>
</p>

KPMG/KPMG/Views/Home/About.cshtml
@{
    ViewBag.Title = "About project";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>Website created for recrutation process</p>

KPMG/KPMG/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<address>
    Kamil Koziel<br />
    Krakow, Poland<br />   
</address>

<address>
    <strong>E-mail:</strong>   <a href="mailto:kl.koziel@gmail.com">kl.koziel[at]gmail.com</a><br />
</address>

KPMG/KPMG/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

KPMG/KPMG/Views/Shared/Filter.cshtml
@model IEnumerable<KPMG.Models.Employee>
    
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fullname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HireDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PerformanceManager)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PerformanceManager.Fullname)
            </td>
        </tr>
    }
</table>

KPMG/KPMG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Employee Info App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Info App", "Index", "Employees", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Kamil Koziel</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/custom")
    @RenderSection("scripts", required: false)
</body>
</html>